---
title: "Untitled"
author: "Anja Shahu"
date: "11/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(rvest)
library(stringr)
library(zoo)
library(directlabels)
library(plotly)
```

```{r}
# download state-level cases and deaths data from nytimes
url <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"
covid <- read_csv(url)

# download policy data
url <- "https://healthdata.gov/sites/default/files/state_policy_updates_20201125_0719.csv"
tmp_filename <- tempfile()
download.file(url, tmp_filename)
policies <- read_csv(tmp_filename)
file.remove(tmp_filename)

# download population data 
url <- "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population"
h <- read_html(url)
```

```{r}
# extract data from wiki population table
population_names <- c("rank_curr", "rank_2010", "state", "pop_2019", "pop_2010", "perc_change", "abs_change", "house_seats", "house_perc", "est_pop_per_elec_vote", "cen_pop_per_seat_2019", "cen_pop_per_seat_2010", "perc_pop_2019", "perc_pop_2010", "perc_pop_change", "perc_of_elec")
population <- h %>% 
  html_nodes("table") %>% 
  .[1] %>% 
  html_table(fill = TRUE) %>% 
  .[[1]] %>% 
  setNames(population_names)

# removed extra row at the top and total rows at the bottom of data frame and row for American Samoa in population data
population <- population %>% 
  slice(2:56) %>% 
  select(state, pop_2019) %>% 
  rename(population = pop_2019)

# remove out [10], [12] and [14] subscripts from last 3 rows and remove commas from population numbers
# also change population to numeric class
population <- population %>% 
  mutate(population = str_replace_all(population, "\\[\\d{2}\\]", ""),
         population = str_replace_all(population, ",", ""),
         population = as.numeric(population))

# change to U.S. Virgin Islands to Virgin Islands to match covid data frame 
population <- population %>% 
   mutate(state = recode(state, 
                         `U.S. Virgin Islands` = "Virgin Islands"))
```

```{r}
# create tidy data for covid data
covid_tidy <- covid %>% 
  gather(measure, cum_count, cases:deaths)

# create 7 day rolling average of cases and deaths
covid_tidy <- covid_tidy %>% 
  group_by(state, measure) %>%
  arrange(state, measure, date) %>%
  mutate(new_count = cum_count - lag(cum_count),
         new_count_7dayavg = rollmean(new_count, k = 7, fill = NA)) %>%
  ungroup()

# join population data to covid data frame
covid_tidy <- covid_tidy %>% left_join(population, by = "state")

# create per 10 million population variables for 7 day average variables
covid_tidy <- covid_tidy %>% 
  mutate(new_count_7dayavg_per_1mil = new_count_7dayavg / (population / 1000000),
         cum_count_per_100thous = cum_count / (population / 100000))
```

```{r}
# change from abbreviated to complete state names in policy data frame
covid_df_state_names <- sort(unique(covid$state))
policies_df_state_names <- c("AL", "AK", "AZ", "AR", "CA", 
                             "CO", "CT", "DE", "DC", "FL", 
                             "GA", "GU", "HI", "ID", "IL", 
                             "IN", "IA", "KS", "KY", "LA", 
                             "ME", "MD", "MA", "MI", "MN", 
                             "MS", "MO", "MT", "NE", "NV", 
                             "NH", "NJ", "NM", "NY", "NC", 
                             "ND", "MP", "OH", "OK", "OR", 
                             "PA", "PR", "RI", "SC", "SD", 
                             "TN", "TX", "UT", "VT", "VI", 
                             "VA", "WA", "WV", "WI", "WY")
key <- setNames(covid_df_state_names, policies_df_state_names)

policies <- policies %>% 
  rename(state = state_id) %>%
  mutate(state = recode(state, !!!key))

# remove county-level policies data to keep only state-level policies 
policies_subset <- policies %>% 
  filter(policy_level == "state") 

# removed row that was incorrectly labeled as state-level policy
policies_subset <- policies_subset %>% 
  filter(is.na(county)) %>% 
  select(-c(source, fips_code, county, policy_level))

# join combined covid and population data with policies data
tidy_df <- covid_tidy %>% 
  left_join(policies_subset, by = c("state", "date"))

# create wide_df for summary tables in app 
wide_df <- tidy_df %>%
  pivot_wider(names_from = measure,
              values_from = c(cum_count, new_count,
                              new_count_7dayavg,
                              new_count_7dayavg_per_1mil, 
                              cum_count_per_100thous))
```

```{r}
# create table with ranks for policies, cum_cases, cum_deaths, cum_cases_per_100thous, and cum_deaths_per_100thous
policies_rank <- policies_subset %>% 
  filter(start_stop == "start") %>%
  group_by(state) %>%
  summarise(n_policy = n()) %>%
  arrange(desc(n_policy)) %>% 
    mutate(rank_policy = as.numeric(rownames(.)), 
           policy_comb = paste0(rank_policy, " (", n_policy, ")")) %>%
  ungroup()

policies_rank_county <- policies %>%
  filter(policy_level == "county", start_stop == "start") %>%
  group_by(state) %>%
  summarise(n_policy_c = n()) %>%
  arrange(desc(n_policy_c)) %>% 
    mutate(rank_policy_c = as.numeric(rownames(.)), 
           policy_comb_c = paste0(rank_policy_c, " (", n_policy_c, ")")) %>%
    ungroup()

cum_ranks <- covid_tidy %>%
  pivot_wider(names_from = measure,
              values_from = c(cum_count, new_count,
                              new_count_7dayavg,
                              new_count_7dayavg_per_1mil, 
                              cum_count_per_100thous)) %>%
  filter(date == max(date)) %>%
  select(state, cum_count_cases, cum_count_deaths,
         cum_count_per_100thous_cases, 
         cum_count_per_100thous_deaths) %>%
  arrange(desc(cum_count_cases)) %>% 
  mutate(rank_cum_cases = as.numeric(rownames(.)),
         cum_cases_comb = paste0(rank_cum_cases, " (",
                                 cum_count_cases, ")")) %>% 
  arrange(desc(cum_count_deaths)) %>%
  mutate(rank_cum_deaths = as.numeric(rownames(.)),
         cum_deaths_comb = paste0(rank_cum_deaths, " (",
                                  cum_count_deaths, ")")) %>%
  arrange(desc(cum_count_per_100thous_cases)) %>% 
  mutate(rank_cum_cases_per_100thous = as.numeric(rownames(.)),
         cum_cases_per_100thous_comb = paste0(rank_cum_cases_per_100thous, " (",
                                              round(cum_count_per_100thous_cases,
                                                    digits = 2), ")")) %>%
  arrange(desc(cum_count_per_100thous_deaths)) %>% 
  mutate(rank_cum_deaths_per_100thous = as.numeric(rownames(.)),
         cum_deaths_per_100thous_comb = paste0(rank_cum_deaths_per_100thous, " (",
                                               round(cum_count_per_100thous_deaths,
                                                     digits = 2), ")"))

rank_table <- policies_rank %>% left_join(cum_ranks, by = "state")
```

```{r}
# import US map data
us_map <- map_data("state")

# update states to match spelling from tidy_df
us_map <- us_map %>% 
  rename(state = region) %>% 
  mutate(state = str_to_title(state)) %>%
  mutate(state = str_replace(state, "District Of Columbia", "District of Columbia"))
```

```{r}
# brainstorm for policy tab in shiny app 
test <- tidy_df %>% 
  filter(state == "Maryland", !is.na(policy_type))

test_pivot <- test %>% 
  pivot_wider(names_from = measure, 
              values_from = c(cum_count, new_count, 
                              new_count_7dayavg,
                              new_count_7dayavg_per_1mil,
                              cum_count_per_100thous))

tidy_df %>% filter(state == "Maryland") %>%
  ggplot(aes(x = date, y = new_count_7dayavg, group = measure)) +
  geom_line() +
  geom_dl(aes(label = measure), method = list("last.points", cex = 0.80)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  geom_vline(data = test, aes(xintercept = date), color = "grey", lty = 2) +
  geom_point(data = test, aes(x = date, y = 15000, color = start_stop)) +
  scale_y_log10(limits = c(1, 15000)) +
  ggtitle("New cases and deaths in Maryland over time") +
  xlab("Date") +
  ylab("Count (7-day average) (log10 scale)") +
  theme_bw() 

p <- tidy_df %>%
  filter(measure == "cases",
         state == c("Maryland", "New York", "North Dakota")) %>%
  ggplot(aes(x = date, y = cum_count, color = state, group = 1,
             text = paste0("Day: ", format(date, format ="%b %d %Y"),
                           "\n", state, ": ", round(cum_count, digits = 3)))) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  geom_line() +
  ggtitle("Cumulative cases over time") +
  xlab("Date") +
  ylab("Cumulative cases") +
  theme_bw() +
  theme(legend.title = element_blank(), legend.position = "")

ggplotly(p, tooltip = c("text"))

g <- tidy_df %>% 
  filter(date == "2020-08-01", measure == "cases") %>%
  left_join(us_map, by = "state") %>%
  ggplot(aes(x = long, y = lat, fill = cum_count_per_100thous, group = group,
             text = paste0("Day: ", format(date, format ="%b %d %Y"),
                           "\n", state, ": ", round(cum_count_per_100thous, digits = 3)))) +
  geom_polygon(color = "white") +
  scale_fill_viridis_c(name = "Cumulative/100k \n(log10)", 
                       trans = "log10",
                       limits = c(1, 15000)) +
  ggtitle("Cumulative cases") +
  theme(panel.grid.major = element_blank(), 
        panel.background = element_blank(),
        axis.title = element_blank(), 
        axis.text = element_blank(),
        axis.ticks = element_blank()) 
ggplotly(g, tooltip = c("text"))

test <- tidy_df %>% filter(measure == "deaths")
```
